### ISSUE TITLE
May 2022 Endgame

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-java-pack#1003]
Legends of status:
Mark | Description
-- | --
✅ | verified
🚢 | shipped/released
✋ | blocked
🏃 | work in progress

#### Extension Pack  
- [x] https://github.com/microsoft/vscode-java-pack/pull/1002

#### Project Manager for Java 
N/A

#### Debugger for Java
verifier: @jdneo
- [x] Provide "Stop Java" button when triggering "Run Java" action. [#1166](https://github.com/microsoft/vscode-java-debug/issues/1166).
- [x] [API] Support DAP request `processId` and event `processid` to get the exact pid of current running Java process. [java-debug#413](https://github.com/microsoft/java-debug/pull/413).
- [x] Naming Java terminals with different names. [#1164](https://github.com/microsoft/vscode-java-debug/issues/1164).
- [x] Enable Java terminal link provider on all terminals. [#1168](https://github.com/microsoft/vscode-java-debug/pull/1168).
- [x] Disable HCR button when running Java without debugging. [#1167](https://github.com/microsoft/vscode-java-debug/pull/1167).

#### Maven for Java
verifier: 
- [x] https://github.com/microsoft/vscode-maven/issues/815

#### Gradle for Java
verifier: @Eskibear 
- [x] https://github.com/microsoft/vscode-gradle/pull/1224#issuecomment-1140776004

#### Test Runner for Java
N/A

#### Spring Boot Dashboard
- [x] https://github.com/microsoft/vscode-spring-boot-dashboard/issues/164

## Verification follow-ups
- [x] Extension Pack
- [x] Debugger for Java
- [x] Maven for Java
- [x] Gradle for Java

Spring Boot Dashboard
  - [x] https://github.com/microsoft/vscode-spring-boot-dashboard/issues/174

## Release
- [x] Extension Pack
- [x] Debugger for Java
- [x] Maven for Java
- [x] Gradle for Java
- [x] Spring Boot Dashboard
