### ISSUE TITLE
November 2022 Endgame

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-pack#1122]
Legends of status:
Mark | Description
-- | --
✅ | verified
🚢 | shipped/released
✋ | blocked
🏃 | work in progress

#### Extension Pack
N/A

#### Debugger for Java
verifier: @jdneo
- [x] Optimize the build error report of "Build failed, do you want to continue?". [#1214](https://github.com/microsoft/vscode-java-debug/issues/1214).
- [x] Use the system encoding to generate the *.argfile. [#1112](https://github.com/microsoft/vscode-java-debug/issues/1112).
- [x] "shortenCommandLine": "argfile|auto" should include "vmArgs". [#1254](https://github.com/microsoft/vscode-java-debug/issues/1254).

#### Maven for Java
N/A

#### Gradle for Java
verifier:

#### Spring Boot Dashboard
verifier:

## Verification follow-ups
- [x] Extension Pack
- [x] Debugger for Java
- [x] Maven for Java
- [x] Gradle for Java
- [x] Spring Boot Dashboard

## Release
- [x] Extension Pack
- [x] Debugger for Java
- [x] Maven for Java
- [x] Gradle for Java
- [x] Spring Boot Dashboard

## Post-Release Tasks
Please update dependencies for each project to avoid vulnerabilities. For any reason not to update, create and track corresponding issues in each repo.
- [x] Extension Pack @Eskibear
- [x] Project Manager for Java @jdneo
- [x] Debugger for Java @testforstephen
- [x] Maven for Java @Eskibear
- [x] Gradle for Java @CsCherrYY
- [x] Test Runner for Java @jdneo
- [x] LSIF Java indexer @CsCherrYY
- [x] Spring Extensions @Eskibear
