### ISSUE TITLE
<Month> 2023 Endgame

### ISSUE THREAD

**Issue by HuyGitgub** [microsoft/vscode-java-pack#1371]
Legends of status:
Mark | Description
-- | --
✅ | verified
🚢 | shipped/released
✋ | blocked
🏃 | work in progress

#### Extension Pack
verifier:

#### Project Manager for Java
verifier:

#### Debugger for Java
verifier:

#### Maven for Java
verifier:

#### Gradle for Java
verifier:

#### Test Runner for Java
verifier:

#### Spring Boot Dashboard
verifier:

## Verification follow-ups
- [ ] Extension Pack
- [ ] Project Manager for Java
- [ ] Debugger for Java
- [ ] Maven for Java
- [ ] Gradle for Java
- [ ] Test Runner for Java
- [ ] Spring Boot Dashboard

## Release
- [ ] Extension Pack
- [ ] Project Manager for Java
- [ ] Debugger for Java
- [ ] Maven for Java
- [ ] Gradle for Java
- [ ] Test Runner for Java
- [ ] Spring Boot Dashboard

## Post-Release Tasks
Please update dependencies for each project to avoid vulnerabilities. For any reason not to update, create and track corresponding issues in each repo.
- [ ] Extension Pack @testforstephen
- [ ] Project Manager for Java @jdneo
- [ ] Debugger for Java @testforstephen
- [ ] Maven for Java @testforstephen
- [ ] Gradle for Java @jdneo
- [ ] Test Runner for Java @jdneo
- [ ] LSIF Java indexer @jdneo
- [ ] Spring Extensions @testforstephen

```[tasklist]
### Tasks
```
