### ISSUE TITLE
Enhance highlighting experience

### ISSUE THREAD

**Issue by Vigilans** [microsoft/vscode-java-pack#270]
This issue tracks a set of java highlighting related issues.

### Bug

- [x] Catch block
  - [x] Multi-exception declaration across multiple lines - https://github.com/microsoft/vscode-java-pack/issues/259
  - [x] Parameter highlighting - https://github.com/atom/language-java/issues/219
- [x] Enum fields - https://github.com/redhat-developer/vscode-java/issues/974
- [x] New expression
  - [x] Tenary operator - https://github.com/atom/language-java/issues/179 
  - [x] Right square brace - https://github.com/atom/language-java/issues/180
  - [x] Arithmetic operators - https://github.com/atom/language-java/issues/192
  - [x] Method dot operator - https://github.com/atom/language-java/issues/213, https://github.com/atom/language-java/issues/181
- [x] Array initializer - https://github.com/redhat-developer/vscode-java/issues/728, https://github.com/atom/language-java/issues/199

### Improvement

- [ ] Consistent highlighting of types - https://github.com/atom/language-java/issues/216
- [x] Semantic highlighting

**Comment by 0dinD** [comment]
Semantic highlighting has been provided by the Java language support extension for quite some time now, and with with the improvements I made in eclipse/eclipse.jdt.ls#1501 consistent highlighting of types has also been achieved. Shouldn't those boxes be checked now? Or is there something specific missing from the semantic highlighting? I have a couple of smaller improvements in mind that I might submit another PR about in the future, but overall I feel like the feature can be considered "done".

**Comment by Eskibear** [comment]
I think we can close this issue, as  "Consistent highlighting of types" is coverred by semantic highlighting.  As for syntax highlighting, PR has been created into upstream repo for a long time (just no one reviews).
