### ISSUE TITLE
New UX of welcome view

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-java-pack#540]
Todo Items:

- [x] Implement a welcome page + tour page. In welcome page, provide shortcuts in group. In tour page, take a tour of main features. (PR #535)
- [x] only pop up tour page when open in first time. (PR #544)
- [x] switch to welcome page automatically after finishing the tour. (PR #541 )
- [x] assign proper screenshots in the tour page. (PR #546)

**Comment by Eskibear** [comment]
Telemetry

- [ ] telemetry for actions (external links, button, tab-switching...)

When there's no open folder:
- [ ] Proper guide in Java Project Explorer, instead of an error message. @jdneo
- [ ] Proper guide/infor in Testing view. @jdneo

visibility of welcome view (@Eskibear )
- [ ] Hide in Codespaces by default.
- [ ] Controlled by A/B testing
