### ISSUE TITLE
Chinese Language Support

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-java-pack#62]
We have lots of Chinese developers. It would be great if we can provide a localized interface. This issue is to track the effort of building the localization story.
Supporting Chinese is a start. Once the solution is working, we can expand the support to other languages.

Here are the issues created to track the progress of related extensions:
- [ ] Java Language Server redhat-developer/vscode-java#716
- [ ] Java Debugger Microsoft/vscode-java-debug#477
- [ ] Maven Microsoft/vscode-maven#46
- [ ] Java Test Runner Microsoft/vscode-java-test#437
- [ ] Java Dependency Viewer Microsoft/vscode-java-dependency#100
