### ISSUE TITLE
improve getting started experience with walkthrough

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-java-pack#692]
### A/B testing hosted by VS Code team
- [x] Make sure the walkthrough page and Java Welcome page won't show at the same time. #700 

### Update walkthrough page:
- [x] The last step will navigate user to the welcome page #698 

### Update the Java Welcome page:
- [x] Change the name to 'Java Help Center' or sth else. #694 
- [x] Section 'Configuration' -> 'General'  #694 
- [x] Set to the default not show #699 

### Update Getting Started page:
- [x] Rename the title to sth like 'Coding and debugging tips for students'  #693 
- [x] Also update the title in the Student section in Java Welcome page #693 
- [x] Remove the part for 'No import needed'  #693
