### ISSUE TITLE
November 2021 Endgame

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-java-pack#819]
Legends of status:
Mark | Description
-- | --
✅ | verified
🚢 | shipped/released
✋ | blocked
🏃 | work in progress

#### Debugger for Java - verifier @jdneo 
- [x] Troubleshooting Guide for Encoding Issues on Windows. See [Troubleshooting_encoding](https://github.com/microsoft/vscode-java-debug/blob/main/Troubleshooting_encoding.md).
- [x] Address encoding issues on Windows. [#1077](https://github.com/microsoft/vscode-java-debug/pull/1077).
- [x] Encoding - launcher.bat could not pass on redirected input into the java program being debugged. [microsoft/vscode-java-pack#756](https://github.com/microsoft/vscode-java-pack/issues/756).
- [x] Encoding - Launching BAT for UTF-8 fix is incompatible with Security Policies disallowing BAT execution. [#646](https://github.com/microsoft/vscode-java-debug/issues/646).
- [x] Encoding - Non-ASCII char support for Windows terminals. [#622](https://github.com/microsoft/vscode-java-debug/issues/622).
- [x] Encoding - [Windows non-ASCII folder] Error: Could not find or load main class. [#623](https://github.com/microsoft/vscode-java-debug/issues/623).
- [x] Contribution from [
John Grant](https://github.com/cyrfer): Support multiline values in envFile. [#1061](https://github.com/microsoft/vscode-java-debug/issues/1061).
- [x] Contribution from [
Adrien Piquerez](https://github.com/adpi2). Fix NPE when using step filter. [microsoft/java-debug#387](https://github.com/microsoft/java-debug/pull/387).

#### Test Runner for Java @Eskibear 
- [x] Can specify `classPaths` in `java.test.config` https://github.com/microsoft/vscode-java-test/issues/1140
- [x] Can specify `envFile` in `java.test.config` https://github.com/microsoft/vscode-java-test/issues/1214
- [x] Can specify `modulePaths` in `java.test.config` https://github.com/microsoft/vscode-java-test/issues/1101
- [x] Can specify `preLaunchTask` in `java.test.config` https://github.com/microsoft/vscode-java-test/issues/1201
- [x] Can jump between tests and test subjects https://github.com/microsoft/vscode-java-test/issues/660
- [x] Test messages will be shown at where it happens https://github.com/microsoft/vscode-java-test/issues/1266

#### Project Manager for Java
N/A

#### Maven for Java
N/A

#### Gradle for Java 
- [x] https://github.com/microsoft/vscode-gradle/issues/1096

## Verification follow-ups

- [x] https://github.com/microsoft/vscode-java-debug/issues/1085

## Release

- [x] Test Runner for Java
- [x] Gradle for Java
- [x] Debugger for Java

## External Contributions
