### ISSUE TITLE
Support platform specific extension

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-pack#845]
Here are some work items in downstream Java extensions to track the support of embedded JRE https://github.com/redhat-developer/vscode-java/issues/2109.

- [x] Keep the runtime requirement check consistent with the RedHat Java extension microsoft/vscode-java-pack#787
- [x] Documentation update about platform specific extension support microsoft/vscode-java-pack#788
- [x] Adjust the minimum JDK requirement in Coding Pack microsoft/vscode-java-pack#789

**Comment by nickzhums** [comment]
For docs, there are multiple pending changes regarding getting started, walkthrough, project manager, etc

**Comment by Eskibear** [comment]
@nickzhums @testforstephen 
Are we going to finish updating related docs in December?

**Comment by nickzhums** [comment]
@Eskibear @testforstephen  is it already released? If so, we should update asap

**Comment by Eskibear** [comment]
https://github.com/microsoft/vscode-docs/pull/5044
